// Station catalogue — 255 stations.
//
// Generated by scripts/merge-soundtap.mjs; edit that, not this.
//
// Upstream is the soundtap.fm catalogue (the soundtap repo's D1 database),
// which carries a station only after probing it live, so those entries are all
// https and were serving audio when soundtap last checked. Stations LyraPod
// already had and soundtap does not list are kept unchanged, http streams
// included — those play here because the kiosk is served over http itself.
//
// Excluded on purpose:
//   - HLS (.m3u8). A bare HTML5 Audio element cannot play a playlist without
//     hls.js, so such an entry is a tile that silently does nothing.
//   - Entries sharing another station's stream url, which is how soundtap
//     records some HD subchannels; two tiles playing identical audio is worse
//     than one.
//   - Stations found dead when every stream here was re-probed on 2026-08-24.
//
// Streams rot. Re-probe with scripts/verify-all-streams.py, and treat its TLS
// failures sceptically: Python's defaults are refused by some Icecast hosts
// that browsers negotiate with fine.

export const DEFAULT_STATIONS = [
  {
    id: "1431am",
    name: "1431AM",
    streamUrl: "https://www.1431am.org:8001/1431high",
    logo: "/logos/1431am.png",
    genre: "Thessaloniki, Greece"
  },
  {
    id: "4zzz",
    name: "4ZZZ",
    streamUrl: "https://iheart.4zzz.org.au/4zzz",
    logo: "/logos/4zzz.svg",
    genre: "Brisbane • Australia"
  },
  {
    id: "bagelradio",
    name: "Bagel Radio",
    streamUrl: "https://ais-sa3.cdnstream1.com/2606_128.aac",
    logo: "/logos/bagelradio.jpg",
    genre: "USA"
  },
  {
    id: "bailriggfm",
    name: "Bailrigg FM",
    streamUrl: "https://stream.bailriggfm.co.uk/listen/bfm/128.mp3",
    logo: "/logos/bailriggfm.png",
    genre: "UK"
  },
  {
    id: "bfffm",
    name: "BFF.fm",
    streamUrl: "https://stream.bff.fm/1/BFF.fm.mp3",
    logo: "/logos/bfffm.png",
    genre: "USA"
  },
  {
    id: "boomradio",
    name: "Boom Radio",
    streamUrl: "https://listen-boomradio.sharp-stream.com/65_boom_radio_live_192",
    genre: "Oldies • United Kingdom"
  },
  {
    id: "bsr",
    name: "BSR",
    streamUrl: "https://listen.bsrlive.com/bsrmp3",
    genre: "Providence"
  },
  {
    id: "bushradio",
    name: "Bushradio",
    streamUrl: "https://zas4.ndx.co.za:9100/stream",
    logo: "/logos/bushradio.png",
    genre: "South Africa"
  },
  {
    id: "bytefm",
    name: "ByteFM",
    streamUrl: "https://uplink.byte.fm/bytefm-main/mp3-128/",
    genre: "Germany"
  },
  {
    id: "cambridge105",
    name: "Cambridge 105",
    streamUrl: "https://stream.cambridge105.co.uk:8443/105-radioplayer-high",
    genre: "Country, Folk • Cambridge"
  },
  {
    id: "cfru",
    name: "CFRU",
    streamUrl: "https://listen.cfru.ca/",
    logo: "/logos/cfru.png",
    genre: "Canada"
  },
  {
    id: "chirp2",
    name: "CHIRP",
    streamUrl: "https://peridot.streamguys1.com:5185/live",
    logo: "/logos/chirp2.png",
    genre: "Independent Radio • USA"
  },
  {
    id: "citr",
    name: "CiTR",
    streamUrl: "https://live.citr.ca/live.aac",
    logo: "/logos/citr.png",
    genre: "U of British Columbia"
  },
  {
    id: "ciut",
    name: "CIUT",
    streamUrl: "https://ice23.securenetsystems.net/CIUT",
    genre: "Toronto"
  },
  {
    id: "cixx",
    name: "CIXX",
    streamUrl: "https://ice23.securenetsystems.net/CIXXFM",
    logo: "/logos/cixx.png",
    genre: "Campus Radio • Canada"
  },
  {
    id: "met-radio-1280-am",
    name: "CJRU",
    streamUrl: "https://ryerson.out.airtime.pro:8000/ryerson_a",
    logo: "/logos/met-radio-1280-am.jpg",
    genre: "Toronto"
  },
  {
    id: "cjsf",
    name: "CJSF",
    streamUrl: "https://www.cjsf.ca/streaming",
    logo: "/logos/cjsf.png",
    genre: "College Radio • Canada"
  },
  {
    id: "cjsw",
    name: "CJSW",
    streamUrl: "https://stream.cjsw.com/cjsw.mp3",
    logo: "/logos/cjsw.png",
    genre: "Campus Radio • Canada"
  },
  {
    id: "ckcu",
    name: "CKCU",
    streamUrl: "https://stream2.statsradio.com:8124/stream",
    logo: "/logos/ckcu.jpg",
    genre: "College Radio • Canada"
  },
  {
    id: "ckms",
    name: "CKMS",
    streamUrl: "https://radiowaterloo.ca/stream2",
    logo: "/logos/ckms.png",
    genre: "Community Radio • Canada"
  },
  {
    id: "ckut",
    name: "CKUT",
    streamUrl: "https://delray.ckut.ca:8001/ckut-live-128",
    logo: "/logos/ckut.png",
    genre: "Montreal Community Radio"
  },
  {
    id: "coyoteradio",
    name: "Coyote Radio",
    streamUrl: "https://crbroadcast.csusb.edu/cr_live",
    logo: "/logos/coyoteradio.png",
    genre: "USA"
  },
  {
    id: "dublab",
    name: "dublab",
    streamUrl: "https://dublab.out.airtime.pro:8000/dublab_a",
    genre: "Live, Variety • United States"
  },
  {
    id: "dublindigitalradio",
    name: "Dublin Digital Radio",
    streamUrl: "https://dublin-digital-radio.radiocult.fm/stream",
    logo: "/logos/dublindigitalradio.jpg",
    genre: "Ireland"
  },
  {
    id: "freeform-portland",
    name: "Freeform Portland",
    streamUrl: "http://listen.freeformportland.org:8000/stream",
    logo: "/logos/freeform-portland.png",
    genre: "Community Driven Radio"
  },
  {
    id: "frquencebanane",
    name: "Fréquence Banane",
    streamUrl: "https://player.frequencebanane.ch/fb_192",
    genre: "Lausanne"
  },
  {
    id: "futureradio",
    name: "Future Radio",
    streamUrl: "https://radio.canstream.co.uk:8007/live.mp3",
    genre: "Rock • United Kingdom"
  },
  {
    id: "humboldt-hot-air",
    name: "Humboldt Hot Air",
    streamUrl: "https://hha.streamguys1.com/live",
    logo: "/logos/humboldt-hot-air.png",
    genre: "Arcata"
  },
  {
    id: "infowars",
    name: "InfoWars",
    streamUrl: "http://stream-mp3.infowars.com/",
    logo: "/logos/infowars.jpg",
    genre: "USA"
  },
  {
    id: "kafm-88-1",
    name: "KAFM",
    streamUrl: "https://streams.radiomast.io/10822f41-b0b3-4430-809f-9c22cf5c990f",
    logo: "/logos/kafm-88-1.jpg",
    genre: "United States"
  },
  {
    id: "kala-hd2",
    name: "KALA-HD2",
    streamUrl: "https://kala.streamguys1.com/live1",
    logo: "/logos/kala-hd2.jpg",
    genre: "Univ. Davenport"
  },
  {
    id: "kalw",
    name: "KALW",
    streamUrl: "https://kalw-live.streamguys1.com/kalw.aac",
    genre: "San Francisco"
  },
  {
    id: "kalx",
    name: "KALX",
    streamUrl: "https://stream.kalx.berkeley.edu:8443/kalx-128.mp3",
    logo: "/logos/kalx.png",
    genre: "UC Berkeley"
  },
  {
    id: "kanm-student-radio",
    name: "KANM",
    streamUrl: "https://icecast.kanm.org/listen",
    logo: "/logos/kanm-student-radio.jpg",
    genre: "Indie, Rock • United States"
  },
  {
    id: "kaos-olympia",
    name: "KAOS",
    streamUrl: "https://s3.myradiostream.com:59506/stream",
    logo: "/logos/kaos-olympia.jpg",
    genre: "Olympia"
  },
  {
    id: "jazz88-fm-88-5-kbem",
    name: "KBEM",
    streamUrl: "https://kbem-live.streamguys1.com/kbem_aac",
    logo: "/logos/jazz88-fm-88-5-kbem.png",
    genre: "Jazz, News • United States"
  },
  {
    id: "kboo-portland",
    name: "KBOO",
    streamUrl: "https://live.kboo.fm:8443/high",
    logo: "/logos/kboo-portland.png",
    genre: "Variety • Portland"
  },
  {
    id: "kbvr-fm-88-7",
    name: "KBVR",
    streamUrl: "https://node-10.zeno.fm/9ympbz9nfa0uv",
    logo: "/logos/kbvr-fm-88-7.png",
    genre: "United States"
  },
  {
    id: "kcaw-sitka",
    name: "KCAW",
    streamUrl: "https://tektite.streamguys1.com:5195/live",
    logo: "/logos/kcaw-sitka.jpg",
    genre: "News • Sitka"
  },
  {
    id: "kcbp",
    name: "KCBP",
    streamUrl: "https://kcbp.broadcasttool.stream/play",
    logo: "/logos/kcbp.png",
    genre: "United States"
  },
  {
    id: "88-3-kcck-cedar-rapids",
    name: "KCCK",
    streamUrl: "https://stream.kcck.org/jazz883kcck",
    logo: "/logos/88-3-kcck-cedar-rapids.jpg",
    genre: "Jazz, News • United States"
  },
  {
    id: "prairie-public",
    name: "KCND",
    streamUrl: "https://18153.live.streamtheworld.com/KCNDFM_SC",
    logo: "/logos/prairie-public.png",
    genre: "Classical, News • United States"
  },
  {
    id: "kcpr",
    name: "KCPR",
    streamUrl: "https://ice9.securenetsystems.net/KCPR1",
    logo: "/logos/kcpr.png",
    genre: "Cal Poly San Luis Obispo"
  },
  {
    id: "kcrw",
    name: "KCRW",
    streamUrl: "https://streams.kcrw.com/kcrw_mp3?aw_0_1st.playerid=radio-browser.info",
    logo: "/logos/kcrw.png",
    genre: "Always on LA"
  },
  {
    id: "kcsb",
    name: "KCSB",
    streamUrl: "https://kcsb.streamguys1.com/live",
    logo: "/logos/kcsb.png",
    genre: "Santa Barbara"
  },
  {
    id: "kcsu",
    name: "KCSU",
    streamUrl: "https://listen.kcsufm.com/stream?nocache=1770828530774",
    logo: "/logos/kcsu.png",
    genre: "University Radio • USA"
  },
  {
    id: "kdrt",
    name: "KDRT",
    streamUrl: "https://kdrt.org:8001/kdrt",
    logo: "/logos/kdrt.png",
    genre: "Davis"
  },
  {
    id: "kdvs",
    name: "KDVS",
    streamUrl: "https://listen.kdvs.org/stream",
    logo: "/logos/kdvs.png",
    genre: "Freeform • Davis, CA"
  },
  {
    id: "kexp",
    name: "KEXP",
    streamUrl: "https://kexp.streamguys1.com/kexp160.aac?listenerid=f4bcb5c771d830fbdd4195088a946ea6&awparams=companionAds%3Atrue",
    logo: "/logos/kexp.png",
    genre: "USA"
  },
  {
    id: "kfai",
    name: "KFAI-FM",
    streamUrl: "https://kfai.broadcasttool.stream/kfai-1",
    logo: "/logos/kfai.png",
    genre: "Minneapolis + St. Paul"
  },
  {
    id: "kfcf-fresno-ca",
    name: "KFCF",
    streamUrl: "https://stream.kfcf.org:8443/128",
    logo: "/logos/kfcf-fresno-ca.png",
    genre: "Fresno, CA"
  },
  {
    id: "kfjc",
    name: "KFJC",
    streamUrl: "https://netcast.kfjc.org/kfjc-128k-mp3",
    logo: "/logos/kfjc.gif",
    genre: "The Wave of the West"
  },
  {
    id: "kfok",
    name: "KFOK",
    streamUrl: "https://kfok.streamguys1.com/live-mp3",
    genre: "United States"
  },
  {
    id: "kgnu",
    name: "KGNU",
    streamUrl: "https://kgnu.streamguys1.com/kgnu",
    logo: "/logos/kgnu.png",
    genre: "Community Radio • USA"
  },
  {
    id: "khdx",
    name: "KHDX Radio",
    streamUrl: "http://streaming.radio.co/s662abb673/listen",
    logo: "/logos/khdx.png",
    genre: "Hendrix College • Conway, AR"
  },
  {
    id: "khol",
    name: "KHOL",
    streamUrl: "http://peridot.streamguys.com:6010/live",
    logo: "/logos/khol.png",
    genre: "Jackson Hole Community Radio"
  },
  {
    id: "khum",
    name: "KHUM",
    streamUrl: "http://lostcoast.streamguys.us/khum-hi",
    logo: "/logos/khum.png",
    genre: "Freeform • Humboldt County"
  },
  {
    id: "kiyu",
    name: "KIYU",
    streamUrl: "https://kiyu.streamguys1.com/live",
    logo: "/logos/kiyu.png",
    genre: "News • Galena"
  },
  {
    id: "kkcr-kaua-i-community-radio",
    name: "KKCR",
    streamUrl: "https://s8.phx.icastcenter.com:9000/stream#.mp3",
    logo: "/logos/kkcr-kaua-i-community-radio.jpg",
    genre: "United States"
  },
  {
    id: "kkup-cupertino",
    name: "KKUP",
    streamUrl: "https://kkup.streamguys1.com/live",
    logo: "/logos/kkup-cupertino.png",
    genre: "Variety • Cupertino"
  },
  {
    id: "kmrd2",
    name: "KMRD",
    streamUrl: "https://kmrd.broadcasttool.stream/listen",
    logo: "/logos/kmrd2.png",
    genre: "Community Radio • USA"
  },
  {
    id: "kmrd",
    name: "KMRD-LP",
    streamUrl: "https://kmrd.broadcasttool.stream/listen.m3u",
    logo: "/logos/kmrd.png",
    genre: "Madrid Community Radio"
  },
  {
    id: "kmsu",
    name: "KMSU",
    streamUrl: "https://stream.aiir.com/ivdkskjmcnhuv",
    logo: "/logos/kmsu.jpg",
    genre: "Mankato"
  },
  {
    id: "kmud",
    name: "KMUD",
    streamUrl: "https://kmud.streamguys1.com/live",
    logo: "/logos/kmud.png",
    genre: "Redwood Community Radio"
  },
  {
    id: "kmun-astoria",
    name: "KMUN",
    streamUrl: "https://ice5.securenetsystems.net/KMUN",
    logo: "/logos/kmun-astoria.png",
    genre: "News • Astoria"
  },
  {
    id: "knhc-seattle-dance-89-5",
    name: "KNHC",
    streamUrl: "https://knhc-ice.streamguys1.com/live",
    logo: "/logos/knhc-seattle-dance-89-5.png",
    genre: "Electronic • Seattle"
  },
  {
    id: "knon",
    name: "KNON",
    streamUrl: "https://knon.streamguys1.com/live",
    logo: "/logos/knon.jpg",
    genre: "Americana, Blues • United States"
  },
  {
    id: "knsj",
    name: "KNSJ",
    streamUrl: "https://music.knsj.org/wp-content/uploads/2026/04/KNSJ-No-Kings-Recap-1.mp3",
    logo: "/logos/knsj.jpg",
    genre: "United States"
  },
  {
    id: "kntu",
    name: "KNTU",
    streamUrl: "https://ice41.securenetsystems.net/KNTU",
    logo: "/logos/kntu.png",
    genre: "Alternative • USA"
  },
  {
    id: "knvc",
    name: "KNVC",
    streamUrl: "https://www.streamcontrol.net:8444/s/16400",
    logo: "/logos/knvc.png",
    genre: "Carson City"
  },
  {
    id: "kopn",
    name: "KOPN",
    streamUrl: "https://kopn.broadcasttool.stream/play",
    logo: "/logos/kopn.jpg",
    genre: "United States"
  },
  {
    id: "koto",
    name: "KOTO",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/KOTOFM.mp3",
    logo: "/logos/koto.png",
    genre: "A Rare Medium, Well-Done"
  },
  {
    id: "kpcc",
    name: "KPCC",
    streamUrl: "https://laist.streamguys1.com/kpcc-mp3?aw_0_1st.playerId=laist",
    genre: "Los Angeles"
  },
  {
    id: "kpfa",
    name: "KPFA",
    streamUrl: "https://streams.kpfa.org:8443/kpfa",
    logo: "/logos/kpfa.png",
    genre: "Vigilant as Always"
  },
  {
    id: "kpov",
    name: "KPOV",
    streamUrl: "https://kpov-ice.streamguys1.com/live",
    logo: "/logos/kpov.png",
    genre: "USA"
  },
  {
    id: "kptz-91-9-port-townsend",
    name: "KPTZ",
    streamUrl: "https://kptz.streamguys1.com/live-aac",
    logo: "/logos/kptz-91-9-port-townsend.jpg",
    genre: "Variety • Port Townsend"
  },
  {
    id: "kqed",
    name: "KQED",
    streamUrl: "https://streams.kqed.org/kqedradio?onsite=true",
    logo: "/logos/kqed.png",
    genre: "Cultural News • USA"
  },
  {
    id: "krbx",
    name: "KRBX",
    streamUrl: "http://radioboise-ice.streamguys1.com/live",
    logo: "/logos/krbx.png",
    genre: "Radio Boise"
  },
  {
    id: "krcc",
    name: "KRCC",
    streamUrl: "https://streams.krcc.org/krcc_mp3",
    logo: "/logos/krcc.ico",
    genre: "Local News • USA"
  },
  {
    id: "krcl",
    name: "KRCL",
    streamUrl: "https://stream.xmission.com/krcl-high",
    logo: "/logos/krcl.jpg",
    genre: "Lake City"
  },
  {
    id: "105-1-krfh",
    name: "KRFH",
    streamUrl: "https://krfh.streamguys1.com",
    logo: "/logos/105-1-krfh.png",
    genre: "United States"
  },
  {
    id: "krnu",
    name: "KRNU",
    streamUrl: "https://s8.yesstreaming.net:17004/krnu",
    logo: "/logos/krnu.png",
    genre: "Alternative • USA"
  },
  {
    id: "marfa-public-radio",
    name: "KRTS",
    streamUrl: "https://marfapr-ice.streamguys1.com/krts",
    logo: "/logos/marfa-public-radio.jpg",
    genre: "News, Talk • Marfa"
  },
  {
    id: "krux",
    name: "KRUX",
    streamUrl: "https://kruxstream.nmsu.edu/KRUX",
    genre: "Las Cruces"
  },
  {
    id: "krvs-public-media",
    name: "KRVS",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/KRVSFMAAC.aac",
    logo: "/logos/krvs-public-media.png",
    genre: "Blues, Jazz • United States"
  },
  {
    id: "the-wave",
    name: "KRWV-LP",
    streamUrl: "https://bigrradio.cdnstream1.com/5208_128",
    logo: "/logos/the-wave.png",
    genre: "Rock • United States"
  },
  {
    id: "krza-88-7-alamosa-taos",
    name: "KRZA",
    streamUrl: "https://crystalout.surfernetwork.com:8001/KRZA-FM_MP3",
    logo: "/logos/krza-88-7-alamosa-taos.jpg",
    genre: "Alamosa"
  },
  {
    id: "ksdp",
    name: "KSDP",
    streamUrl: "https://stream.apradio.org/stream.aac",
    logo: "/logos/ksdp.png",
    genre: "Community Radio • USA"
  },
  {
    id: "ksdt",
    name: "KSDT",
    streamUrl: "https://s4.radio.co/s2c33c7adb/listen",
    genre: "College Radio • USA"
  },
  {
    id: "ksjd",
    name: "KSJD",
    streamUrl: "https://war.streamguys1.com:8435/",
    logo: "/logos/ksjd.jpg",
    genre: "Cortez"
  },
  {
    id: "ksjs",
    name: "KSJS",
    streamUrl: "https://streaming.ksjs.sjsu.edu/",
    logo: "/logos/ksjs.png",
    genre: "Student Run 24/7 Ground Zero"
  },
  {
    id: "ksko",
    name: "KSKO",
    streamUrl: "https://ksko.streamguys1.com/live",
    logo: "/logos/ksko.jpg",
    genre: "News, Talk • United States"
  },
  {
    id: "kspc",
    name: "KSPC",
    streamUrl: "https://kspc.radioca.st/stream?type=http&nocache=41177",
    logo: "/logos/kspc.png",
    genre: "College Radio • Los Angeles"
  },
  {
    id: "k-squid",
    name: "KSQD",
    streamUrl: "https://ksqd.info:8100/stream",
    genre: "News • United States"
  },
  {
    id: "ksua",
    name: "KSUA",
    streamUrl: "https://stream.radio.co/se776fab22/listen",
    genre: "Fairbanks"
  },
  {
    id: "ksut-four-corners-public-radio",
    name: "KSUT Four Corners Public Radio",
    streamUrl: "https://ksut.streamguys1.com/ksut",
    logo: "/logos/ksut-four-corners-public-radio.png",
    genre: "Classical, Indigenous • Radio Ignacio"
  },
  {
    id: "ktal-lp",
    name: "KTAL",
    streamUrl: "https://ktal.broadcasttool.stream/stream",
    logo: "/logos/ktal-lp.jpg",
    genre: "United States"
  },
  {
    id: "ktcu",
    name: "KTCU",
    streamUrl: "https://ktcustream.tcu.edu/",
    logo: "/logos/ktcu.png",
    genre: "College • USA"
  },
  {
    id: "ktna",
    name: "KTNA",
    streamUrl: "https://ktna.broadcasttool.stream/play",
    logo: "/logos/ktna.jpg",
    genre: "News • Talkeetna"
  },
  {
    id: "ktru",
    name: "KTRU",
    streamUrl: "https://n02-us.rcs.revma.com/uevdenv2ss8uv?rj-ttl=5&rj-tok=AAABn78SYC4AzgfQIzfMM4PbLg",
    logo: "/logos/ktru.png",
    genre: "Houston"
  },
  {
    id: "ktsw-fm-89-9-san-marcos",
    name: "KTSW",
    streamUrl: "https://ktswlive.txstate.edu:8102/listen",
    logo: "/logos/ktsw-fm-89-9-san-marcos.jpg",
    genre: "United States"
  },
  {
    id: "kuci",
    name: "KUCI",
    streamUrl: "https://streamer.kuci.org/high",
    logo: "/logos/kuci.png",
    genre: "KUCI 88.9 FM • UC Irvine"
  },
  {
    id: "kunm",
    name: "KUNM",
    streamUrl: "https://29325.live.streamtheworld.com/KUNMFM_128.mp3",
    logo: "/logos/kunm.png",
    genre: "USA"
  },
  {
    id: "jazz-and-more",
    name: "KUNV",
    streamUrl: "https://kunv.oit.unlv.edu/stream/1/",
    logo: "/logos/jazz-and-more.png",
    genre: "United States"
  },
  {
    id: "kuoi",
    name: "KUOI-FM",
    streamUrl: "https://s2.radio.co/sedf30688d/listen",
    logo: "/logos/kuoi.png",
    genre: "University of Idaho"
  },
  {
    id: "kups",
    name: "KUPS",
    streamUrl: "https://streamingv2.shoutcast.com/kupsfm",
    logo: "/logos/kups.png",
    genre: "The Sound"
  },
  {
    id: "kuvo",
    name: "KUVO",
    streamUrl: "https://kuvo.streamguys1.com/kuvo-mp3-128",
    logo: "/logos/kuvo.png",
    genre: "Jazz, News • Denver"
  },
  {
    id: "kvcu-radio-1190",
    name: "KVCU",
    streamUrl: "https://radio.garden/api/ara/content/listen/vxqa6HTr/channel.mp3?1730758410709",
    logo: "/logos/kvcu-radio-1190.png",
    genre: "United States"
  },
  {
    id: "91-3-kvlu-beaumont",
    name: "KVLU",
    streamUrl: "https://kvlustream.lamar.edu:8443/stream",
    logo: "/logos/91-3-kvlu-beaumont.png",
    genre: "News • Beaumont"
  },
  {
    id: "kvmr",
    name: "KVMR",
    streamUrl: "https://sslstream.kvmr.org:9433/aac96#.mp3",
    logo: "/logos/kvmr.png",
    genre: "Comunity • USA"
  },
  {
    id: "kvnf",
    name: "KVNF",
    streamUrl: "https://peridot.streamguys1.com:7145/live.mp3",
    logo: "/logos/kvnf.png",
    genre: "Paonia"
  },
  {
    id: "kwmr-90-5-89-9",
    name: "KWMR",
    streamUrl: "https://listen.kwmr.org/live",
    logo: "/logos/kwmr-90-5-89-9.png",
    genre: "United States"
  },
  {
    id: "kwtf",
    name: "KWTF",
    streamUrl: "https://s35.myradiostream.com:33726/listen.mp3?nocache=1785616487",
    genre: "Santa Rosa"
  },
  {
    id: "kwvh",
    name: "KWVH",
    streamUrl: "https://ice41.securenetsystems.net/KWVH",
    genre: "United States"
  },
  {
    id: "kxci",
    name: "KXCI",
    streamUrl: "https://kxci.broadcasttool.stream:80/play",
    logo: "/logos/kxci.png",
    genre: "Tucson's Community Radio"
  },
  {
    id: "kxlu",
    name: "KXLU",
    streamUrl: "https://kxlu.streamguys1.com/kxlu-hi",
    logo: "/logos/kxlu.png",
    genre: "Los Angeles"
  },
  {
    id: "kxsf-lp",
    name: "KXSF",
    streamUrl: "https://streams.radio.co/sd1bcd1376/listen#.mp3",
    logo: "/logos/kxsf-lp.jpg",
    genre: "Country, Electronic • United States"
  },
  {
    id: "kxua",
    name: "KXUA",
    streamUrl: "https://listen.kxua.com/stream",
    logo: "/logos/kxua.png",
    genre: "Fayetteville"
  },
  {
    id: "kzfr",
    name: "KZFR",
    streamUrl: "https://listen.kzfr.org/stream",
    logo: "/logos/kzfr.png",
    genre: "Chico"
  },
  {
    id: "kzmu",
    name: "KZMU",
    streamUrl: "https://kzmu.streamguys1.com/live",
    logo: "/logos/kzmu.jpg",
    genre: "USA"
  },
  {
    id: "kzsc",
    name: "KZSC",
    streamUrl: "https://kzscfms1-geckohost.radioca.st/kzschigh",
    logo: "/logos/kzsc.png",
    genre: "Santa Cruz • 88.1 FM"
  },
  {
    id: "kzsu",
    name: "KZSU",
    streamUrl: "https://kzsu-streams.stanford.edu/kzsu-1-128.mp3",
    genre: "Palo Alto"
  },
  {
    id: "kzum",
    name: "KZUM",
    streamUrl: "http://us4.internet-radio.com:8030/stream",
    logo: "/logos/kzum.png",
    genre: "Local Radio • Lincoln, NE"
  },
  {
    id: "lemellotron",
    name: "LeMellotron",
    streamUrl: "https://listen.radioking.com/radio/477719/stream/534044",
    logo: "/logos/lemellotron.png",
    genre: "France"
  },
  {
    id: "luxuriamusic",
    name: "Luxuria Music",
    streamUrl: "https://ice10.securenetsystems.net/LUXOTRON",
    logo: "/logos/luxuriamusic.png",
    genre: "Electronic • USA"
  },
  {
    id: "nessradio",
    name: "Ness Radio",
    streamUrl: "https://radio.nessradio.net:8212/nessradio-hd",
    logo: "/logos/nessradio.jpg",
    genre: "Morocco"
  },
  {
    id: "newtownradio",
    name: "Newtown Radio",
    streamUrl: "https://streaming.radio.co/s0d090ee43/listen",
    logo: "/logos/newtownradio.ico",
    genre: "USA"
  },
  {
    id: "nts1",
    name: "NTS 1",
    streamUrl: "https://stream-relay-geo.ntslive.net/stream",
    logo: "/logos/nts.png",
    genre: "NTS Radio • London"
  },
  {
    id: "nts2",
    name: "NTS 2",
    streamUrl: "https://stream-relay-geo.ntslive.net/stream2",
    logo: "/logos/nts.png",
    genre: "NTS Radio • Channel 2"
  },
  {
    id: "ohiofm",
    name: "OHIO FM",
    streamUrl: "https://stream.radio.co/s5f6fd6c6f/listen",
    genre: "Columbus"
  },
  {
    id: "purefm",
    name: "Pure FM",
    streamUrl: "https://redbeemedia.streamabc.net/redbm-tipik-mp3-160-1909468?sABC=6n6r4so4%230%239q45sp5988805pn765865n1s09r186p3%23ei&aw_0_1st.playerid=rv&amsparams=playerid:rv;skey:1785614260",
    genre: "Belgium"
  },
  {
    id: "radio6023",
    name: "Radio 6023",
    streamUrl: "https://stream12.top-ix.org/radio6023",
    logo: "/logos/radio6023.jpg",
    genre: "Italy"
  },
  {
    id: "radioactive2",
    name: "Radio Active",
    streamUrl: "https://streamyourdream.org:8050/radioactive",
    logo: "/logos/radioactive2.png",
    genre: "Greece"
  },
  {
    id: "radiocampuslille",
    name: "Radio Campus Lille",
    streamUrl: "https://radiocampuslille.ice.infomaniak.ch/radiocampuslille-128",
    logo: "/logos/radiocampuslille.png",
    genre: "France"
  },
  {
    id: "radiocardiff",
    name: "Radio Cardiff",
    streamUrl: "https://radiocardiff.radioca.st/stream",
    genre: "United Kingdom"
  },
  {
    id: "radiocentraal",
    name: "Radio Centraal",
    streamUrl: "https://streams.movemedia.eu/centraal",
    logo: "/logos/radiocentraal.ico",
    genre: "Belgium"
  },
  {
    id: "radiodepaul",
    name: "Radio Depaul",
    streamUrl: "https://ice26.securenetsystems.net/RADIODEPAUL",
    genre: "United States"
  },
  {
    id: "radiodio",
    name: "Radio Dio",
    streamUrl: "https://live.aurafm.org/RadioDio",
    logo: "/logos/radiodio.ico",
    genre: "Dub • France"
  },
  {
    id: "radio-free-brooklyn",
    name: "Radio Free Brooklyn",
    streamUrl: "https://patmos.cdnstream.com/proxy/ttenney1/?mp=/listen&esPlayer&cb=239941.mp3",
    logo: "/logos/radio-free-brooklyn.png",
    genre: "What Brooklyn Sounds Like"
  },
  {
    id: "radionova",
    name: "Radio Nova",
    streamUrl: "https://novazz.ice.infomaniak.ch/novazz-128.mp3",
    logo: "/logos/radionova.png",
    genre: "France"
  },
  {
    id: "radioone91fm",
    name: "Radio One 91FM",
    streamUrl: "https://play.r1.co.nz/live",
    logo: "/logos/radioone91fm.png",
    genre: "Community Radio • New Zealand"
  },
  {
    id: "radioparadise",
    name: "Radio Paradise",
    streamUrl: "https://stream.radioparadise.com/mp3-320",
    logo: "/logos/radioparadise.png",
    genre: "Community radio"
  },
  {
    id: "radiogrenouille",
    name: "RadioGrenouille",
    streamUrl: "https://live.radiogrenouille.com:8443/live",
    genre: "France"
  },
  {
    id: "radiok",
    name: "RadioK",
    streamUrl: "https://radiok.broadcasttool.stream/play_256",
    logo: "/logos/radiok.gif",
    genre: "Campus • USA"
  },
  {
    id: "radiostadmontfoort",
    name: "RadioStadMontfoort",
    streamUrl: "http://stream001.digiplay.nl:9038/stream",
    logo: "/logos/radiostadmontfoort.png",
    genre: "24/7 • Netherlands"
  },
  {
    id: "radyobilkent",
    name: "Radyo Bilkent",
    streamUrl: "https://stream.netradyom.com/listen/radyobilkent/radio.mp3",
    genre: "Türkiye"
  },
  {
    id: "radyoeksen",
    name: "Radyo Eksen",
    streamUrl: "https://eksenwmp.radyotvonline.com/;stream.mp3",
    logo: "/logos/radyoeksen.png",
    genre: "Alternative • Türkiye"
  },
  {
    id: "radyoodtu",
    name: "Radyo ODTU",
    streamUrl: "https://stream3.radyoodtu.com.tr/;",
    genre: "Türkiye"
  },
  {
    id: "rinsefm",
    name: "Rinse FM",
    streamUrl: "https://admin.stream.rinse.fm/proxy/rinse_uk/stream",
    genre: "United Kingdom"
  },
  {
    id: "rtrfm",
    name: "RTRfm",
    streamUrl: "https://live.rtrfm.com.au/stream1",
    logo: "/logos/rtrfm.webp",
    genre: "Australia"
  },
  {
    id: "sohoradio",
    name: "Soho Radio",
    streamUrl: "https://sohoradiomusic.doughunt.co.uk:8010/128mp3",
    logo: "/logos/sohoradio.jpg",
    genre: "Culture • UK"
  },
  {
    id: "soundartradio",
    name: "Soundart Radio",
    streamUrl: "https://radio.canstream.co.uk:8134/live.mp3",
    genre: "Electronic, Experimental • United Kingdom"
  },
  {
    id: "thelion",
    name: "The LION",
    streamUrl: "https://n08.radiojar.com/k9uw1tyr7x8uv?rj-ttl=5&rj-tok=AAABn78SpfgAgyTHTkzCBY06rQ",
    genre: "University Park"
  },
  {
    id: "the-roots-fm",
    name: "The Roots FM",
    streamUrl: "https://ice6.securenetsystems.net/ROOTS2",
    logo: "/logos/the-roots-fm.png",
    genre: "United States"
  },
  {
    id: "thewolf",
    name: "The Wolf",
    streamUrl: "https://cloud.revma.ihrhls.com/zc4101?rj-org=n12b-e2&rj-ttl=5&rj-tok=AAABn78TYj0AO0RtoxEFjaWcYA",
    genre: "Carrollton"
  },
  {
    id: "tropico-fm",
    name: "Tropico FM",
    streamUrl: "https://kffi.broadcasttool.stream/stream",
    logo: "/logos/tropico-fm.png",
    genre: "United States"
  },
  {
    id: "tube-city-online-radio",
    name: "Tube City Online Radio",
    streamUrl: "https://tubecityonline.out.airtime.pro/tubecityonline_a",
    logo: "/logos/tube-city-online-radio.png",
    genre: "News • United States"
  },
  {
    id: "uclaradio",
    name: "UCLAradio",
    streamUrl: "https://live.uclaradio.com/listen/ucla_radio/radio.mp3",
    logo: "/logos/uclaradio.png",
    genre: "USA"
  },
  {
    id: "volnafm",
    name: "Volna FM",
    streamUrl: "https://listen5.myradio24.com/nvolna",
    genre: "Electronic, Pop • Russia"
  },
  {
    id: "wayo",
    name: "WAYO",
    streamUrl: "http://streaming.wayofm.org:8000/wayo-192",
    logo: "/logos/wayo.png",
    genre: "Way Out, Right Here"
  },
  {
    id: "wbcrlp",
    name: "WBCR-lp",
    streamUrl: "https://s3.citrus3.com:8114/stream",
    logo: "/logos/wbcrlp.png",
    genre: "USA"
  },
  {
    id: "wber",
    name: "WBER",
    streamUrl: "https://radio.monroe.edu/wber.mp3",
    logo: "/logos/wber.jpg",
    genre: "Alternative Rock • USA"
  },
  {
    id: "wbny",
    name: "WBNY",
    streamUrl: "http://136.183.9.38:3307/;",
    logo: "/logos/wbny.png",
    genre: "College Radio • USA"
  },
  {
    id: "wbor",
    name: "WBOR",
    streamUrl: "https://listen.wbor.org/",
    logo: "/logos/wbor.png",
    genre: "College • USA"
  },
  {
    id: "wcbn",
    name: "WCBN",
    streamUrl: "https://floyd.wcbn.org:8443/wcbn-hd.mp3",
    logo: "/logos/wcbn.png",
    genre: "FM Ann Arbor"
  },
  {
    id: "wcdb",
    name: "WCDB",
    streamUrl: "https://streams.wcdb.fm/stream",
    logo: "/logos/wcdb.jpg",
    genre: "24/7 • USA"
  },
  {
    id: "wcfa",
    name: "WCFA",
    streamUrl: "https://wcfa.broadcasttool.stream/play",
    logo: "/logos/wcfa.jpg",
    genre: "United States"
  },
  {
    id: "wchc",
    name: "WCHC",
    streamUrl: "https://s2.radio.co/sc161fe4c9/listen",
    logo: "/logos/wchc.png",
    genre: "Alternative • USA"
  },
  {
    id: "wcom-lp-carrboro-community-radio-cooperative",
    name: "WCOM",
    streamUrl: "https://audio-mp3.ibiblio.org/wcom-hifi.mp3",
    logo: "/logos/wcom-lp-carrboro-community-radio-cooperative.png",
    genre: "Carrboro"
  },
  {
    id: "wcuw",
    name: "WCUW",
    streamUrl: "https://wcuw.org/wp-content/uploads/2026/07/Speilberg_Porter-fundraiser-aired-8-6-26.mp3",
    logo: "/logos/wcuw.png",
    genre: "Americana • USA"
  },
  {
    id: "wdbm",
    name: "WDBM",
    streamUrl: "https://play.impact89fm.org:8000/impact89fm",
    logo: "/logos/wdbm.png",
    genre: "Alternative • USA"
  },
  {
    id: "wdce-richmond",
    name: "WDCE",
    streamUrl: "https://streaming.live365.com/a39711",
    logo: "/logos/wdce-richmond.jpg",
    genre: "Richmond"
  },
  {
    id: "wdcr",
    name: "WDCR",
    streamUrl: "https://14223.live.streamtheworld.com/DC_RADIO.mp3",
    genre: "Hanover"
  },
  {
    id: "wdcv",
    name: "WDCV-FM",
    streamUrl: "https://us2.internet-radio.com/proxy/wdcvfm?mp=/live",
    logo: "/logos/wdcv.png",
    genre: "Voice of Dickinson College"
  },
  {
    id: "wdiy",
    name: "WDIY",
    streamUrl: "https://war.streamguys1.com:7883/wdiy_7880",
    genre: "Lehigh Valley"
  },
  {
    id: "wdrt",
    name: "WDRT",
    streamUrl: "https://audio.wdrt.org:8000/high",
    genre: "Viroqua"
  },
  {
    id: "weft",
    name: "WEFT",
    streamUrl: "https://weft.broadcasttool.stream/stream",
    logo: "/logos/weft.jpg",
    genre: "USA"
  },
  {
    id: "95-7-fm-welt",
    name: "WELT",
    streamUrl: "https://stream.laut.fm/irrlichts-welt",
    logo: "/logos/95-7-fm-welt.png",
    genre: "Noise • Germany"
  },
  {
    id: "wers",
    name: "WERS",
    streamUrl: "http://marconi.emerson.edu:8000/wers",
    logo: "/logos/wers.png",
    genre: "Alternative • USA"
  },
  {
    id: "88-1-wesu-middletown",
    name: "WESU",
    streamUrl: "https://listen.wesufm.org/stream",
    logo: "/logos/88-1-wesu-middletown.gif",
    genre: "News, Syndicated • Middletown"
  },
  {
    id: "wets-americana",
    name: "WETS Americana",
    streamUrl: "https://wets-fm.streamguys1.com/live-2",
    genre: "Americana, News • United States"
  },
  {
    id: "wets-news",
    name: "WETS News",
    streamUrl: "https://wets-fm.streamguys1.com/live-3",
    genre: "News • United States"
  },
  {
    id: "wevl-memphis",
    name: "WEVL",
    streamUrl: "https://wevl.streamguys1.com/live",
    logo: "/logos/wevl-memphis.jpg",
    genre: "Hip-hop, Rock • Memphis"
  },
  {
    id: "wfmu",
    name: "WFMU",
    streamUrl: "https://stream0.wfmu.org/freeform-128k",
    logo: "/logos/wfmu.svg",
    genre: "Freeform • Jersey City"
  },
  {
    id: "wfuv",
    name: "WFUV",
    streamUrl: "https://onair.wfuv.org/onair-aacplus",
    logo: "/logos/wfuv.ico",
    genre: "Adult Album Alternative • USA"
  },
  {
    id: "whav-lp",
    name: "WHAV",
    streamUrl: "https://whav.streamguys1.com/live",
    logo: "/logos/whav-lp.jpg",
    genre: "Oldies • United States"
  },
  {
    id: "whcl",
    name: "WHCL",
    streamUrl: "https://wchl.streamon.fm/wchl-24k.aac",
    genre: "News • Chapel Hill"
  },
  {
    id: "whrb",
    name: "WHRB",
    streamUrl: "https://stream.whrb.org/whrb-he-aac",
    logo: "/logos/whrb.png",
    genre: "Cambridge"
  },
  {
    id: "whrv",
    name: "WHRV",
    streamUrl: "http://whrv.mediaplayer.whro.org/128",
    logo: "/logos/whrv.png",
    genre: "Jazz • USA"
  },
  {
    id: "whrw",
    name: "WHRW",
    streamUrl: "https://stream.whrwfm.org:8443/new",
    logo: "/logos/whrw.png",
    genre: "Classical • USA"
  },
  {
    id: "wicb",
    name: "WICB",
    streamUrl: "https://icecast.do.zufall.co/wicb_mp3_high",
    genre: "Ithaca"
  },
  {
    id: "90-5-wicn-fm",
    name: "WICN",
    streamUrl: "https://wicn-ice.streamguys1.com/live-mp3",
    logo: "/logos/90-5-wicn-fm.gif",
    genre: "Blues, Folk • United States"
  },
  {
    id: "widr",
    name: "WIDR",
    streamUrl: "https://widrfm.net/stream",
    logo: "/logos/widr.png",
    genre: "USA"
  },
  {
    id: "witr",
    name: "WITR",
    streamUrl: "https://streaming.witr.rit.edu/live-aac-96",
    logo: "/logos/witr.jpg",
    genre: "College Radio • USA"
  },
  {
    id: "wkcr",
    name: "WKCR",
    streamUrl: "https://wkcr.streamguys1.com//live",
    logo: "/logos/wkcr.png",
    genre: "New York"
  },
  {
    id: "wknc",
    name: "WKNC",
    streamUrl: "https://das-edge62-live365-dal03.cdnstream.com/a30009",
    logo: "/logos/wknc.png",
    genre: "NC State College Radio"
  },
  {
    id: "wknc-hd-2-raleigh",
    name: "WKNC-HD2",
    streamUrl: "https://streaming.live365.com/a45877",
    logo: "/logos/wknc-hd-2-raleigh.png",
    genre: "Blues, Classical • United States"
  },
  {
    id: "wluw2",
    name: "WLUW",
    streamUrl: "https://ice26.securenetsystems.net/WLUW?playSessionID=AD47E8CB-E610-56AC-09E96DB77F17E09B",
    logo: "/logos/wluw2.webp",
    genre: "Independent Radio • USA"
  },
  {
    id: "wmbr",
    name: "WMBR",
    streamUrl: "http://wmbr.org:8000/hi",
    logo: "/logos/wmbr.png",
    genre: "MIT Campus Radio"
  },
  {
    id: "wmcn",
    name: "WMCN",
    streamUrl: "https://audio-edge-vqwx4.yyz.g.radiomast.io/0786c562-432d-4d2b-a4b6-fda1a2f60cf7",
    logo: "/logos/wmcn.png",
    genre: "United States"
  },
  {
    id: "wmhb",
    name: "WMHB",
    streamUrl: "https://streaming.live365.com/a46702",
    logo: "/logos/wmhb.png",
    genre: "Rock, Talk • United States"
  },
  {
    id: "wmmt",
    name: "WMMT",
    streamUrl: "https://aurora.shoutca.st/radio/8200/radio.mp3?",
    logo: "/logos/wmmt.png",
    genre: "Variety • United States"
  },
  {
    id: "wmnf",
    name: "WMNF",
    streamUrl: "https://stream.wmnf.org/wmnf_high_quality",
    logo: "/logos/wmnf.png",
    genre: "Community Radio • USA"
  },
  {
    id: "wmrw",
    name: "WMRW-LP",
    streamUrl: "http://69.54.28.12:8951/listen",
    logo: "/logos/wmrw.png",
    genre: "LP Warren"
  },
  {
    id: "wmsc",
    name: "WMSC",
    streamUrl: "https://peridot.streamguys1.com:5485/live-mp3",
    logo: "/logos/wmsc.png",
    genre: "Rock • Upper Montclair"
  },
  {
    id: "wmtu",
    name: "WMTU",
    streamUrl: "https://stream.wmtu.fm/wmtu-live",
    logo: "/logos/wmtu.webp",
    genre: "USA"
  },
  {
    id: "91-1-fm-wmua",
    name: "WMUA",
    streamUrl: "https://usa5.fastcast4u.com/proxy/qernhlca?mp=/1",
    genre: "United States"
  },
  {
    id: "wncu-fm-90-7-durham",
    name: "WNCU",
    streamUrl: "https://wncu.streamguys1.com/live",
    genre: "Jazz • United States"
  },
  {
    id: "wncw",
    name: "WNCW",
    streamUrl: "https://wncw-live-a.edge.audiocdn.com/6286_56k.aac",
    genre: "Spindale"
  },
  {
    id: "wnmc",
    name: "WNMC",
    streamUrl: "https://s4.yesstreaming.net:17170/stream",
    logo: "/logos/wnmc.jpg",
    genre: "United States"
  },
  {
    id: "wnur",
    name: "WNUR",
    streamUrl: "https://n04-us.rcs.revma.com/w4pmmfkdx4zuv?rj-ttl=5&rj-tok=AAABn78TEPcANOKXDRa9_kW5Og",
    genre: "Chicago"
  },
  {
    id: "wnyc",
    name: "WNYC",
    streamUrl: "https://fm939.wnyc.org/wnycfm.mp3",
    logo: "/logos/wnyc.png",
    genre: "News • USA"
  },
  {
    id: "wnyu",
    name: "WNYU",
    streamUrl: "https://www.wnyu-ice-cast-relay.com/wnyu.mp3",
    genre: "New York"
  },
  {
    id: "worldmusicradio",
    name: "World Music Radio",
    streamUrl: "http://stream.wlmm.dk:8010/wmrmp3",
    logo: "/logos/worldmusicradio.png",
    genre: "Denmark"
  },
  {
    id: "worldwidefm",
    name: "Worldwide FM",
    streamUrl: "https://worldwide-fm.radiocult.fm/stream",
    genre: "Electronic, Jazz • United Kingdom"
  },
  {
    id: "wort",
    name: "WORT",
    streamUrl: "https://stream.wortfm.org:8443/high.mp3",
    logo: "/logos/wort.png",
    genre: "USA"
  },
  {
    id: "wowd",
    name: "WOWD",
    streamUrl: "https://wowd.broadcasttool.stream/stream",
    logo: "/logos/wowd.jpg",
    genre: "Variety • United States"
  },
  {
    id: "wpkn-89-5-fm-bridgeport",
    name: "WPKN",
    streamUrl: "https://ice25.securenetsystems.net/WPKN",
    logo: "/logos/wpkn-89-5-fm-bridgeport.png",
    genre: "Talk • United States"
  },
  {
    id: "wppm-lp-philadelphia",
    name: "WPPM",
    streamUrl: "https://phillycam.radioca.st/stream",
    logo: "/logos/wppm-lp-philadelphia.jpg",
    genre: "Philadelphia"
  },
  {
    id: "wprb-princeton",
    name: "WPRB",
    streamUrl: "https://wprb.streamguys1.com/live",
    logo: "/logos/wprb-princeton.png",
    genre: "Indie, Variety • Princeton"
  },
  {
    id: "wprk",
    name: "WPRK",
    streamUrl: "https://wprk.broadcasttool.stream:80/stream",
    logo: "/logos/wprk.png",
    genre: "USA"
  },
  {
    id: "wpts",
    name: "WPTS",
    streamUrl: "http://audio.wpts.pitt.edu:8000/wpts_live_128s.mp3",
    logo: "/logos/wpts.png",
    genre: "Alternative • USA"
  },
  {
    id: "wras",
    name: "WRAS",
    streamUrl: "https://gpb.streamguys1.com/gpb-atlanta-mp3-website",
    logo: "/logos/wras.png",
    genre: "Album 88 • Georgia State"
  },
  {
    id: "wrbb",
    name: "WRBB",
    streamUrl: "https://audio-edge-qse4n.yyz.g.radiomast.io/dafd1179-5404-4939-9c1c-a014c6964254",
    logo: "/logos/wrbb.png",
    genre: "College Radio • USA"
  },
  {
    id: "wrfl",
    name: "WRFL",
    streamUrl: "https://wrfl.fm:8002/stream/1",
    genre: "Lexington"
  },
  {
    id: "wrir",
    name: "WRIR",
    streamUrl: "http://files.wrir.org:8000/WRIR96kbps",
    logo: "/logos/wrir.png",
    genre: "Richmond Independent Radio"
  },
  {
    id: "wriu",
    name: "WRIU",
    streamUrl: "https://main-auto.wriu.org/listen/wriu-fm/radio.mp3",
    genre: "Kingston"
  },
  {
    id: "wrpi",
    name: "WRPI",
    streamUrl: "https://stream.wrpi.org/mp3-320.mp3",
    logo: "/logos/wrpi.png",
    genre: "College • USA"
  },
  {
    id: "wruv",
    name: "WRUV",
    streamUrl: "http://icecast.uvm.edu:8005/wruv_fm_256",
    logo: "/logos/wruv.png",
    genre: "WRUV 90.1 FM"
  },
  {
    id: "wrvu",
    name: "WRVU",
    streamUrl: "https://streaming.wrvu.org/live",
    genre: "Nashville"
  },
  {
    id: "scr",
    name: "WSCR",
    streamUrl: "https://stream.abacast.net/direct/audacy-wscrfmmp3-imc",
    logo: "/logos/scr.jpg",
    genre: "Sports, Talk • United States"
  },
  {
    id: "wsoe",
    name: "WSOE",
    streamUrl: "https://audio-mp3.ibiblio.org/wsoe.mp3",
    logo: "/logos/wsoe.webp",
    genre: "Alternative • USA"
  },
  {
    id: "wtip",
    name: "WTIP",
    streamUrl: "https://wtip.broadcasttool.stream/stream",
    logo: "/logos/wtip.png",
    genre: "Community Radio • USA"
  },
  {
    id: "wtul",
    name: "WTUL",
    streamUrl: "https://stream.wtulneworleans.com/",
    logo: "/logos/wtul.png",
    genre: "New Orleans"
  },
  {
    id: "wumm",
    name: "WUMM",
    streamUrl: "http://wumm.machias.edu:8000/wumm",
    logo: "/logos/wumm.png",
    genre: "University • USA"
  },
  {
    id: "wusb",
    name: "WUSB",
    streamUrl: "https://stream.wusb.stonybrook.edu:8092/listen.pl/relay?type=http",
    genre: "Stonybrook"
  },
  {
    id: "wvbr",
    name: "WVBR",
    streamUrl: "https://das-edge14-live365-dal02.cdnstream.com/a25496",
    logo: "/logos/wvbr.ico",
    genre: "College Radio • USA"
  },
  {
    id: "wvew",
    name: "WVEW",
    streamUrl: "https://audio-edge-n9hx8.yul.o.radiomast.io/20b6f77f-2177-46a2-b461-437a84273d5f",
    logo: "/logos/wvew.jpg",
    genre: "Brattleboro"
  },
  {
    id: "wvkr",
    name: "WVKR",
    streamUrl: "https://26733.live.streamtheworld.com/WVKRFM.mp3",
    logo: "/logos/wvkr.png",
    genre: "College • USA"
  },
  {
    id: "wvud",
    name: "WVUD",
    streamUrl: "https://streaming.radio.co/s1bc6bf517/listen",
    logo: "/logos/wvud.png",
    genre: "USA"
  },
  {
    id: "wwoz-new-orleans",
    name: "WWOZ",
    streamUrl: "https://wwoz-sc.streamguys1.com/wwozhd2-hi",
    logo: "/logos/wwoz-new-orleans.jpg",
    genre: "New Orleans"
  },
  {
    id: "wwuh",
    name: "WWUH",
    streamUrl: "https://stream3477.egihosting.com:8002/;?type=http&nocache=27523",
    logo: "/logos/wwuh.jpg",
    genre: "United States"
  },
  {
    id: "wxdu",
    name: "WXDU",
    streamUrl: "http://152.3.0.231:8000/wxdu128.mp3",
    logo: "/logos/wxdu.ico",
    genre: "Duke • USA"
  },
  {
    id: "wxou",
    name: "WXOU",
    streamUrl: "https://a8.asurahosting.com/listen/wxou/radio.mp3",
    logo: "/logos/wxou.png",
    genre: "College Radio • USA"
  },
  {
    id: "wxox",
    name: "WXOX",
    streamUrl: "https://patmos.cdnstream.com/proxy/artfmin1/?mp=/stream",
    logo: "/logos/wxox.jpg",
    genre: "Variety • USA"
  },
  {
    id: "wxpr",
    name: "WXPR",
    streamUrl: "https://amber.streamguys1.com:4372/wxpr2",
    logo: "/logos/wxpr.jpg",
    genre: "News • Rhinelander"
  },
  {
    id: "wxyc",
    name: "WXYC",
    streamUrl: "https://audio-mp3.ibiblio.org/wxyc.mp3",
    logo: "/logos/wxyc.png",
    genre: "Freeform • USA"
  },
  {
    id: "wyar",
    name: "WYAR",
    streamUrl: "https://stationplaylist.com:7124/listen.mp3",
    logo: "/logos/wyar.jpg",
    genre: "Jazz, Oldies • United States"
  },
  {
    id: "wysu",
    name: "WYSU",
    streamUrl: "https://live.streamguys1.com:3181/hd2",
    genre: "Classical • USA"
  },
  {
    id: "wyxr",
    name: "WYXR",
    streamUrl: "https://crosstown.streamguys1.com:80/live",
    logo: "/logos/wyxr.png",
    genre: "Arts, Variety • United States"
  },
  {
    id: "wzbc",
    name: "WZBC",
    streamUrl: "https://stream.wzbc.org/wzbc",
    logo: "/logos/wzbc.png",
    genre: "Boston College"
  },
  {
    id: "wzbt",
    name: "WZBT 91.1",
    streamUrl: "https://wzbt.streamguys1.com/live",
    logo: "/logos/wzbt.png",
    genre: "Gettysburg's Best New Music"
  },
  {
    id: "wzrd-chicago",
    name: "WZRD",
    streamUrl: "https://wzrd.streamguys1.com/live",
    logo: "/logos/wzrd-chicago.jpg",
    genre: "United States"
  },
  {
    id: "xrayfm",
    name: "XRAY FM",
    streamUrl: "https://listen.xray.fm/stream",
    logo: "/logos/xrayfm.png",
    genre: "USA"
  },
  {
    id: "ynotradio",
    name: "YNOT Radio",
    streamUrl: "https://das-edge16-live365-dal02.cdnstream.com/a54553",
    logo: "/logos/ynotradio.ico",
    genre: "USA"
  }
];

export default DEFAULT_STATIONS;
